quarkus.http.root-path=/api

# OIDC configuration
quarkus.oidc.auth-server-url=http://localhost:8081/realms/master
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.application-type=web-app

# Logout support
#quarkus.oidc.logout.path=/logout
#quarkus.oidc.logout.post-logout-path=/

# Enable role-based security
quarkus.oidc.roles.role-claim-path=realm_access.roles

quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
